Repository JianLoong/word-cloud-generator, pull requests merged in 2022-10, with the labels that each got.

#8 consistent names and ids
  index.html
Labels: hacktoberfest2022, hacktober-accepted

#13 Added capitalisation settings
  index.html
  src/index.js
Labels: hacktoberfest2022, hacktober-accepted

#16 Improvements on the way the string is tokenized
  package-lock.json
  package.json
  src/worker/process.js
Labels: hacktoberfest2022, hacktoberfest-accepted

#17 #1 - Added more colour options
  dist/main.js
  images/BrBG.png
  images/Greys.png
  images/Oranges.png
  images/PuOr.png
  images/Purples.png
  images/magma.png
  index.html
  src/index.js
Labels: hacktoberfest-accepted
